# Generated by Django 5.2.8 on 2025-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
