# Generated by Django 5.2.8 on 2025-11-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0003_city_authority_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='authority',
            name='city',
        ),
        migrations.AddField(
            model_name='authority',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='museum.authoritytype'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
