# Generated by Django 5.2.8 on 2025-11-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_authoritytype_remove_authority_city_authority_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='museum/')),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum.authority')),
            ],
        ),
    ]
