# Generated by Django 5.2.8 on 2025-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_museum'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='museum',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
