# Generated by Django 5.2.8 on 2025-12-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_museum_close_time_museum_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
